<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="NewsEvents.aspx.cs" Inherits="FujiTecIntranetPortal.NewsEvents" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeaderContent" runat="server">
    <style type="text/css">
        .footer {
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
            background-color: white;
            color: white;
            text-align: center;
            height: 2.5%;
        }

        p {
            background-color: #CF2331;
        }

        .auto-style2 {
            width: 17%;
            height: 30px;
            font-family: Verdana;
        }

        .myInput:focus {
            border: solid 1px green !important;
            outline: double !important;
            font-family: Verdana;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="BodyContent" runat="server">
    <asp:HiddenField ID="hdfilepath" runat="server" />
    <div class="page-container scroll-y">
        <div>
            <h3 class="text-center" style="font-family: Verdana">News & Events</h3>
            <table class="normal_grid">

                <tr>
                    <th class="auto-style2"><strong>Event Description: <span class="hlt-txt">*</span></strong>
                    </th>
                    <td class="auto-style2">
                        <asp:TextBox ID="txtEventName" CssClass="myInput" runat="server" Width="232px" TabIndex="1" Height="60px" TextMode="MultiLine" Style="margin-left: 0"></asp:TextBox>
                    </td>
                    <th class="auto-style2"><strong>Select Photo: <span class="hlt-txt">*</span></strong>
                    </th>
                    <td class="auto-style2">
                        <asp:FileUpload ID="FileUpload1" runat="server" TabIndex="2" MaxFileSize="10485760"/><asp:Button ID="btnUpload" runat="server" Text="Upload" OnClick="btnUpload_Click" Visible="false" />
                       <asp:Label ID="Label3" runat="server" BackColor="Yellow" ForeColor="Red" Text="Maximum file size should be 300 KB"></asp:Label>
                        <br />
                       
                        <%--<asp:CustomValidator ID="CustomValidator1" OnServerValidate="ValidateFileSize" ForeColor="Red" runat="server" />--%>
                    </td>
                    <td> <asp:Label ID="Label1" runat="server" BackColor="Yellow" ForeColor="Red" Text="Please upload a landscape photos only  for better view."></asp:Label><br />
                         <asp:Label ID="Label2" runat="server" BackColor="Yellow" ForeColor="Red" Text="(Avoid collage and portrait photos)."></asp:Label>
                    </td>

                </tr>
                
            </table>
        </div>

        <%--      <div style="width: 90%">
            <table>
                <tr>
                    <td class="auto-style2" colspan="3" align="center">

                        <asp:Button ID="btnAdd" runat="server" Text="Add" CssClass="myInput"
                            TabIndex="12" OnClick="btnAdd_Click"></asp:Button>
                        <asp:Button ID="btnAddClear" runat="server" Text="Clear" CssClass="myInput"
                            TabIndex="13" OnClick="btnAddClear_Click"></asp:Button>
                    </td>

                </tr>
                <tr>
                    <td class="auto-style2" colspan="3" align="center">
                        <asp:Label ID="Label1" runat="server" Text=""></asp:Label></td>
                </tr>

            </table>
        </div>
       <div>
            <asp:GridView ID="DGVADD" runat="server" OnSelectedIndexChanged="GV_SelectedIndexChanged" AutoGenerateDeleteButton="True" OnRowDeleting="GV_RowDeleting" OnRowDataBound="GV_OnRowDataBound">

            </asp:GridView>
        </div>--%>

        <div style="width: 90%">
            <table>
                <tr>
                    <td class="auto-style2" colspan="3" align="center">

                        <asp:Button ID="btnSave" runat="server" Text="Save" CssClass="myInput"
                            TabIndex="12" OnClick="btnUpload_Click"></asp:Button>
                        <%-- <asp:Button ID="btnUpdate" runat="server" Text="Update" CssClass="myInput"
                            TabIndex="12" OnClick="btnUpdate_Click"></asp:Button>--%>
                        <asp:Button ID="btnClear" runat="server" Text="Clear" CssClass="myInput"
                            TabIndex="13" OnClick="btnClear_Click"></asp:Button>
                        <%--<asp:Button ID="btnback" runat="server" Text="Go To Dashboardpage" CssClass="myInput"
                            TabIndex="14" OnClick="btnback_Click"></asp:Button>--%>
                    </td>

                </tr>
                <tr>
                    <td class="auto-style2" colspan="3" align="center">
                        <asp:Label ID="lblmsg" runat="server" Text=""></asp:Label></td>
                </tr>

            </table>
        </div>
        <div>
            <div id="divGridViewScroll" style="width: 100%; height: 300px; overflow: scroll">
                <asp:GridView ID="gv" runat="server" AutoGenerateSelectButton="false" OnSelectedIndexChanged="GV_SelectedIndexChanged" Font-Names="Verdana"
                    OnPageIndexChanging="OnPageIndexChanging" AllowPaging="true" PageSize="10" GridLines="Both" HeaderStyle-BorderStyle="Solid"
                    HeaderStyle-BackColor="#9AD6ED" AlternatingRowStyle-BackColor="WhiteSmoke" RowStyle-BorderStyle="Solid" BorderStyle="Solid" FooterStyle-BorderStyle="Solid"
                    HeaderStyle-Height="50px" 
                    AutoGenerateDeleteButton="true" OnRowDeleting="GV_RowDeleting" OnRowDataBound="GV_OnRowDataBound"  HeaderStyle-Font-Names="Verdana">
                </asp:GridView>
            </div>
        </div>
    </div>
</asp:Content>
<asp:Content ID="Content3" ContentPlaceHolderID="FooterContent" runat="server">
    <div class="footer">
        <p style="text-align: left; color: white">
            <strong>Developed by Information Technology.    
    <span style="float: right; color: white">© 2022 Fujitec India Pvt,Ltd.
    </span>
            </strong>
        </p>
    </div>
</asp:Content>

